// Auto-generated by `wrangler types` — edit to add custom bindings.
interface Env {
	/**
	 * Numerai API public ID for authenticated requests.
	 * Set via: npx wrangler secret put NUMERAI_PUBLIC_ID
	 */
	NUMERAI_PUBLIC_ID?: string;

	/**
	 * Numerai API secret key for authenticated requests.
	 * Set via: npx wrangler secret put NUMERAI_SECRET_KEY
	 */
	NUMERAI_SECRET_KEY?: string;

	/** Durable Object namespace — bound automatically by wrangler from wrangler.jsonc */
	MCP_OBJECT: DurableObjectNamespace;
}
